[GLOBAL]
pants_version = "2.8.0rc0"
backend_packages.add = [
  "pants.backend.experimental.go",
]

[source]
root_patterns = ["/"]

[anonymous-telemetry]
enabled = true
repo_id = "45CFC0CB-3242-4E29-8F8F-036E49DE1D7D"

[golang]
expected_version = "1.17"

